#!/usr/bin/env bash
# =============================================================================
# KhodroYar toolchain bootstrap — installs everything needed to build the APK
# on a machine that only has access to github.com, pypi.org and npmjs.org.
#   tools used: JDK21 (pypi jdk4py), build-tools 30.0.3 (AOSP prebuilt mirror),
#   android-34 android.jar (Sable/android-platforms), kotlinc (npm kotlin-compiler)
# =============================================================================
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OPT="${KHODROYAR_TOOLS_HOME:-/opt/android}"
mkdir -p "$OPT"

echo "==> [1/4] JDK 21 via PyPI (jdk4py)"
python3 -m pip install --break-system-packages --quiet "jdk4py==21.0.8.2" || \
    python3 -m pip install --quiet "jdk4py==21.0.8.2"
JAVA_BIN="$(python3 - <<'PY'
import jdk4py, pathlib
p = pathlib.Path(str(jdk4py.JAVA)) 
print(p.parent / "java" if False else jdk4py.JAVA)
PY
)"
# jdk4py exposes JAVA (java binary); tools live next to it
JAVA_HOME_DIR="$(dirname "$JAVA_BIN")"
echo "   java: $JAVA_BIN"

echo "==> [2/4] Android build-tools 30.0.3 (AOSP prebuilt mirror)"
if [ ! -x "$OPT/bt/30.0.3/aapt2" ]; then
    git clone --depth 1 --filter=blob:none --sparse \
        https://github.com/CodeLinaro-mirror/la_platform_prebuilts_fullsdk-linux_build-tools "$OPT/bt-tmp"
    ( cd "$OPT/bt-tmp" && git sparse-checkout set 30.0.3 && mv 30.0.3 "$OPT/bt30" && cd .. && mv bt30 bt )
    mkdir -p "$OPT/bt"
    mv "$OPT/bt-tmp/30.0.3" "$OPT/bt/30.0.3"
    rm -rf "$OPT/bt-tmp"
fi

echo "==> [3/4] android-34 platform (android.jar)"
if [ ! -f "$OPT/sable/android-34/android.jar" ]; then
    git clone --depth 1 --filter=blob:none --no-checkout \
        https://github.com/Sable/android-platforms "$OPT/sable"
    ( cd "$OPT/sable" \
      && git sparse-checkout init --no-cone \
      && printf 'android-34/android.jar\n' | git sparse-checkout set --stdin \
      && git checkout -q )
fi

echo "==> [4/4] Kotlin compiler (npm)"
if [ ! -f "$OPT/kotlinc/lib/kotlin-compiler.jar" ]; then
    VER=$(npm view kotlin-compiler version)
    curl -s -o "$OPT/kotlin-compiler.tgz" "https://registry.npmjs.org/kotlin-compiler/-/kotlin-compiler-$VER.tgz"
    mkdir -p "$OPT/kotlinc"
    tar xzf "$OPT/kotlin-compiler.tgz" -C "$OPT/kotlinc" --strip-components=1
    rm -f "$OPT/kotlin-compiler.tgz"
fi

cat > "$ROOT/tools/env.sh" <<EOF
# KhodroYar Android build environment (generated by tools/setup_env.sh)
export ANDROID_TOOLS=$OPT
export BT=\$ANDROID_TOOLS/bt/30.0.3
export PLATFORM=\$ANDROID_TOOLS/sable/android-34/android.jar
export JAVA_BIN=$JAVA_BIN
export KOTLIN_COMPILER_JAR=\$ANDROID_TOOLS/kotlinc/lib/kotlin-compiler.jar
export KOTLIN_STDLIB=\$ANDROID_TOOLS/kotlinc/lib/kotlin-stdlib.jar
EOF

echo "==> done. Now: cd $ROOT && ./build_apk.sh"
